module.exports = {
    STORMPATH_CLIENT_APIKEY_ID: "6P3EYD6W8WSNVVOOGMLI4NFAQ",
    STORMPATH_CLIENT_APIKEY_SECRET: "UsiTtQxWSJNyCEjoN7mPrBWkvn3i0hwBtQ6Bhclg2JM",
    STORMPATH_APPLICATION_HREF: "https://api.stormpath.com/v1/applications/5dVyGk3BiLjIWUZ5g93y5K"
}
